### PR TITLE
English-Translation

### PR DESCRIPTION
**Pull request by PatrickMAdmin**
Renombrado archivos en y Dir a inglés y traducción inicial completa. ¿Espera que esto ayude?

### CODE REVIEW

**Review by runtimevic — APPROVED** [review]
Thank you very much for the collaboration and the help to have the documentation in English...

**Review by runtimevic — CHANGES_REQUESTED** [review]
Thank you very much for the collaboration and the help to have the documentation in English...

**Review by runtimevic — APPROVED** [review]

**Review by runtimevic — APPROVED** [review]

**Review by runtimevic — APPROVED** [review]
aprobado

**Comment by PatrickMAdmin** [comment]
Me pregunto por qué dice que hay conflictos. Soy nuevo en Git.
Gracias

**Comment by runtimevic** [comment]
Hi @PatrickMAdmin ,
I don't know, I'm not an expert in Git and Github either,
send me everything you've modified by email and I'll paste it and I'll close this request...

**Comment by runtimevic** [comment]
Hello @PatrickMAdmin ,
send me everything you've modified by email and I'll paste it and I'll close this request...
email: victorduranm@hotmail.com

**Review by runtimevic — APPROVED** [review]

**Pull request closed without merging**
